"""
MCP Tools for OpenHands Antigravity Integration.
Exposes autonomous coding capabilities and artifact retrieval to MCP Unified.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Optional

from .bridge import get_openhands_bridge
from .context import get_antigravity_context


async def openhands_run_task(
    prompt: str,
    title: Optional[str] = None,
    conversation_id: Optional[str] = None,
    timeout_seconds: int = 600,
    sync_to_walkthrough: bool = False,
) -> Dict[str, Any]:
    """
    Delegate an autonomous coding/research task to OpenHands.
    Writes the execution artifact directly to the Antigravity Brain Artifacts directory (~/.gemini/antigravity-ide/brain/<conversation_id>/)
    and returns a clean, structured summary for the Antigravity Chat IDE.

    Args:
        prompt: Detailed instructions for OpenHands.
        title: Optional title for the task report.
        conversation_id: Optional Antigravity conversation ID. If omitted, auto-detected from IDE session.
        timeout_seconds: Maximum execution time in seconds (default 600).
        sync_to_walkthrough: If True, also updates walkthrough.md in Antigravity Brain.

    Returns:
        Dict containing task_id, status, duration_seconds, artifact_path, and chat_summary.
    """
    bridge = get_openhands_bridge()
    result = await bridge.execute_task(
        prompt=prompt,
        title=title,
        conversation_id=conversation_id,
        timeout_seconds=timeout_seconds,
        sync_to_walkthrough=sync_to_walkthrough,
    )
    return {
        "task_id": result["task_id"],
        "status": result["status"],
        "duration_seconds": result["duration_seconds"],
        "artifact_path": result["artifact_path"],
        "chat_summary": result["chat_summary"],
    }


async def openhands_get_artifact(
    task_id: str,
    conversation_id: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Retrieve the full Markdown artifact generated by an OpenHands task.

    Args:
        task_id: ID of the OpenHands task (e.g. task-a1b2c3d4).
        conversation_id: Optional Antigravity conversation ID.

    Returns:
        Dict containing content (Markdown), file_path, and found (bool).
    """
    context = get_antigravity_context(conversation_id=conversation_id)
    target_file = context.get_artifact_file(f"openhands_{task_id}.md")

    if target_file.exists():
        content = target_file.read_text(encoding="utf-8")
        return {
            "found": True,
            "task_id": task_id,
            "file_path": str(target_file),
            "content": content,
        }

    # Fallback to in-memory history if file not yet written
    bridge = get_openhands_bridge()
    report = bridge.get_task_report(task_id)
    if report:
        from .formatter import OpenHandsArtifactFormatter
        content = OpenHandsArtifactFormatter.render_markdown_artifact(report)
        return {
            "found": True,
            "task_id": task_id,
            "file_path": str(target_file),
            "content": content,
        }

    return {
        "found": False,
        "task_id": task_id,
        "error": f"Artifact for task {task_id} not found in {context.artifact_dir}",
    }


async def openhands_list_runs() -> List[Dict[str, Any]]:
    """
    List recent OpenHands execution runs in the current session.
    """
    bridge = get_openhands_bridge()
    return bridge.list_tasks()


def get_openhands_tools() -> list:
    """Return list of tool functions for registration in MCP Unified."""
    return [
        openhands_run_task,
        openhands_get_artifact,
        openhands_list_runs,
    ]
